### ISSUE TITLE
Move social and add as one of the category

### ISSUE THREAD

**Issue by paragasu** [phisoft/quaydental-web#4]
![image](https://user-images.githubusercontent.com/27353/89986229-d25dbc00-dcae-11ea-9151-96145ee51e44.png)

jeff take the social out and add as one of the category here

![image](https://user-images.githubusercontent.com/27353/89986247-d689d980-dcae-11ea-8c5a-1fa6d5c7b2d5.png)

here. so that 3 categories more balance

**Comment by qoszira15** [comment]
Done.
