### ISSUE TITLE
Adjust horizontal line

### ISSUE THREAD

**Issue by paragasu** [phisoft/quaydental-web#47]
Line is too bold and out of place. need to adjust the intensity and color

<img width="1750" alt="image" src="https://user-images.githubusercontent.com/27353/96547117-1b00a980-12de-11eb-8d70-22a14a0c8e3b.png">

**Comment by izahshahirah** [comment]
ini contoh yang mereka mahu ikut Sir @paragasu 

<img width="1805" alt="Screenshot 2020-10-20 at 5 03 53 PM" src="https://user-images.githubusercontent.com/60636305/96564913-4d1e0580-12f6-11eb-875d-e299d9580dc6.png">
