### ISSUE TITLE
Update background image

### ISSUE THREAD

**Issue by paragasu** [phisoft/quaydental-web#49]
- [x] Mobile version
![quay_webbanner-02](https://user-images.githubusercontent.com/27353/97667140-2dd36500-1aba-11eb-9ffe-6dc548922ab0.jpg)

- [x] Desktop version
![quay_webbanner-01](https://user-images.githubusercontent.com/27353/97667156-35930980-1aba-11eb-88a6-dc923ce32553.jpg)

**Comment by izahshahirah** [comment]
done
